apiVersion: do.movetokube.com/v1alpha1
kind: DNS
metadata:
  name: example-dns
spec:
  # common fields for most records
  recordType: A
  # name of a record, usually the hostname
  hostname: www
  value:
    # this will take IP address of an ingress from the same namespace
    ref:
      ingressName: nameOfIngress
    literal: 192.168.2.1
  ttl: 3600
  # specific for SRV records only
  port: 80
  # specific for SRV and MX
  priority: 100
  # specific for CAA records only
  flags: 0
  tag: issue

