apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: dns.do.movetokube.com
spec:
  group: do.movetokube.com
  names:
    kind: DNS
    listKind: DNSList
    plural: dns
    singular: dns
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            domainName:
              type: string
            flag:
              format: int64
              type: integer
            hostname:
              type: string
            port:
              format: int64
              type: integer
            priority:
              format: int64
              type: integer
            recordType:
              type: string
            tag:
              type: string
            ttl:
              format: int64
              type: integer
            value:
              properties:
                literal:
                  type: string
              required:
              - literal
              type: object
            weight:
              format: int64
              type: integer
          required:
          - domainName
          - recordType
          - hostname
          - value
          type: object
        status:
          properties:
            id:
              format: int64
              type: integer
            state:
              type: string
          required:
          - state
          - id
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
